import React, { createContext, useContext, useState, useCallback, useEffect } from 'react';
import { fetchAllMarketData } from '../services/indianMarketService';

const MarketContext = createContext(null);
/* eslint-disable react-refresh/only-export-components */

const CACHE_KEY = 'market_cache';
const CACHE_DURATION = 15 * 60 * 1000; // 15 minutes

export function MarketProvider({ children }) {
    const [marketData, setMarketData] = useState(null);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState(null);
    const [lastFetch, setLastFetch] = useState(null);

    const loadMarketData = useCallback(async (forceRefresh = false) => {
        // Check cache first
        if (!forceRefresh) {
            try {
                const cached = localStorage.getItem(CACHE_KEY);
                if (cached) {
                    const parsed = JSON.parse(cached);
                    if (Date.now() - parsed.fetchedAt < CACHE_DURATION) {
                        console.log('[MarketContext] Using cached data');
                        setMarketData(parsed);
                        setLoading(false);
                        setLastFetch(parsed.fetchedAt);
                        return;
                    }
                }
            } catch {
                console.warn('[MarketContext] Cache read failed');
            }
        }

        setLoading(true);
        setError(null);

        try {
            const data = await fetchAllMarketData();
            setMarketData(data);
            setLastFetch(Date.now());

            // Save to cache
            localStorage.setItem(CACHE_KEY, JSON.stringify(data));

            console.log('[MarketContext] ✅ Market data loaded');
        } catch (err) {
            console.error('[MarketContext] ❌ Failed to load market data:', err);

            // Fallback to stale cache (up to 4 hours)
            try {
                const cached = localStorage.getItem(CACHE_KEY);
                if (cached) {
                    const parsed = JSON.parse(cached);
                    const age = Date.now() - parsed.fetchedAt;

                    console.log(`[MarketContext] Using stale cache due to fetch error (Age: ${(age/60000).toFixed(0)}m)`);
                    setMarketData(parsed);
                    setLastFetch(parsed.fetchedAt);

                    if (age > 4 * 60 * 60 * 1000) {
                        setError('Network error. Data is expired (>4h).');
                    } else {
                        setError('Network error. Showing cached data.');
                    }
                } else {
                    // Try ultimate fallback: Static JSON (generated by backend script)
                    try {
                        const resp = await fetch('/data/market_snapshot.json');
                        if (resp.ok) {
                            const snapshot = await resp.json();
                            if (snapshot && snapshot.indices && snapshot.indices.length > 0) {
                                console.log('[MarketContext] Using static snapshot fallback');
                                setMarketData(snapshot);
                                const generated = snapshot.generatedAt || snapshot.generated_at;
                                setLastFetch(generated ? new Date(generated).getTime() : Date.now());
                                setError('Using offline snapshot (Live data failed)');
                                return;
                            }
                        }
                    } catch (staticErr) {
                        console.warn('Static fallback failed', staticErr);
                    }
                    setError(err.message);
                }
            } catch {
                setError(err.message);
            }
        } finally {
            setLoading(false);
        }
    }, []);

    useEffect(() => {
        loadMarketData();
    }, [loadMarketData]);

    const refreshMarket = useCallback(() => {
        return loadMarketData(true);
    }, [loadMarketData]);

    return (
        <MarketContext.Provider value={{
            marketData,
            loading,
            error,
            lastFetch,
            refreshMarket
        }}>
            {children}
        </MarketContext.Provider>
    );
}

export function useMarket() {
    const context = useContext(MarketContext);
    if (!context) {
        throw new Error('useMarket must be used within MarketProvider');
    }
    return context;
}
